# Site settings
title: Daisyproducer
email: your-email@domain.com
description: "An integrated production management system for accessible media."
baseurl: ""
url: "http://www.daisyproducer.org"
copyright: Swiss Library for the Blind, Visually Impaired and Print Disabled
github_username:  sbsdev

# Build settings
markdown: kramdown
permalink: pretty
