# Site settings
title: Daisyproducer
description: "An integrated production management system for accessible media."
baseurl: "http://sbsdev.github.io/daisyproducer/"
url: "http://www.daisyproducer.org"
copyright: Swiss Library for the Blind, Visually Impaired and Print Disabled
github_username:  sbsdev

# Build settings
markdown: kramdown
permalink: pretty
