#!/bin/sh

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
INSTALLDIR=/path/to/daisyproducer
SPOOL_DIR=/var/spool/daisyproducer
VERBOSITY=3

# Import ABACUS product data
cd $INSTALLDIR
python manage.py importABACUS --verbosity=$VERBOSITY $SPOOL_DIR/SN_Alfresco_*.xml
