#!/bin/sh

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
INSTALLDIR=/path/to/daisyproducer
SPOOL_DIR=/var/spool/daisyproducer
VERBOSITY=1

pidfile=/tmp/daisyproducerImportABACUSProductData.pid

if [ -e $pidfile ]; then
    pid=`cat $pidfile`
    if /bin/kill -0 $pid > /dev/null 2>&1; then
	echo "Already running"
	exit 1
    else
	rm $pidfile
    fi
fi
echo $$ > $pidfile

# get all files older than 10 minutes
files=`find $SPOOL_DIR -type f -mmin +10 -name 'SN_Alfresco_*.xml'`

# Import ABACUS product data
cd $INSTALLDIR
python manage.py importABACUS --verbosity=$VERBOSITY $files

rm -f $pidfile
