#+TITLE:     Daisy Producer
#+AUTHOR:    Christian Egli
#+EMAIL:     christian.egli@sbszh.ch
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:1 \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc

* What is it?

Daisy Producer is a system to help you manage the production process
of accessible media. It assumes that you are transforming the content
from hard copy or any electronic format to DTBook XML. Once you have
the DTBook XML the Daisy Pipeline and liblouis can be used to generate
Daisy Talking Books, Large Print and Braille in a fully automated way.

Daisy producer mainly tracks the status of the transformation process
and helps you manage your artifacts that are needed in the
transformation process.

For the generation of accessible media Daisy Producer offers a nice
interface however the work is essentially done by the Daisy Pipeline
and liblouis. 

* Documentation

Daisy Producer comes with built in documentation. See the Help link in
your installation.

* Publications

The [[./daisyproducerSlides.pdf][slides]] from the presentation at the [[http://www.daisy2009.de/en/welcome.html][Daisy 2009 technical conference]]
and a [[./daisyproducerPaper.pdf][paper about Daisy Producer]] are available.

* Download

No release has been produced as of yet. Get the source directly from
the [[https://github.com/sbsdev/daisyproducer][repository]].

* Development

Development of Daisy Producer is done in git. See the [[https://github.com/sbsdev/daisyproducer][github project
pages]] for instructions on how to get the source code.

